<?php

namespace AppBundle\Repository;

/**
 * HeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadRepository extends \Doctrine\ORM\EntityRepository
{
}