<?php

namespace AppBundle\Repository;

/**
 * KeysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeysRepository extends \Doctrine\ORM\EntityRepository
{
}